### ISSUE TITLE
FR8: Create a chat box UI

### ISSUE THREAD

**Issue by maiselkelly** [WSU-4110/Roomiez#13]
|FR8: Create a chat box UI|
|---|
|**Goal**: Roomiez will have a fully functioning chat feature for communication between potential roommates|
|**Stakeholders:** Customers|
| **Description:** When potential roommates are matched, they will be able to chat with each other to get to know each other better and make a personal connection before living together. It will be set up in a similar way to a regular messaging app and the chats will be saved to the database until the user wants to delete any chats. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/23/2020|
  |**Priority:** 2 |

**Comment by ashrityschool** [comment]
Made this look like a Facebook feed where all of the posts are listed.
