### ISSUE TITLE
FR10: Help bar link on home page

### ISSUE THREAD

**Issue by maiselkelly** [WSU-4110/Roomiez#15]
|FR10: Help bar link on home page|
|---|
|**Goal**: To give the user some assistance when they need it|
|**Stakeholders:** Customers|
| **Description:** If users have any sort of confusion or problem with any features of the application, they will be able to communicate with owners of Roomiez. There will be a help button on the chat page to open up the email feature that will assist the user.|
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/23/2020|
  |**Priority:** 2 |

**Comment by ashrityschool** [comment]
Keeps logging user out whenever I submit a question through the Help Bar.
