### ISSUE TITLE
FR12: Functional Chat Wall Feature - Form Submission

### ISSUE THREAD

**Issue by maiselkelly** [WSU-4110/Roomiez#18]
|FR12: Functional Chat Wall Feature -Form Submission |
|---|
|**Goal**: To be able to effectively communicate with potential roommates through this feature and create a potential connection|
|**Stakeholders:** Customers|
| **Description:** Users will be able to chat with potential roommates when they get matched. The chat page will follow the similar functionality of a "Facebook wall" . All of the messages will be stored in the database until the user wants to delete any messages on the wall.|
| **Origin:** Based on initial project specification document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/23/2020|  
|**Priority:** 2 |

**Comment by ashrityschool** [comment]
Used a similar style to the log in interface to maintain the modern and clean aesthetic.
