### ISSUE TITLE
FR14:  Route for user to pick matches by who is online

### ISSUE THREAD

**Issue by maiselkelly** [WSU-4110/Roomiez#20]
|FR14:  Route for user to pick matches by who is online|
|---|
|**Goal**: To be able to select other users according to those that are online.|
|**Stakeholders:** Customers|
| **Description:*Users would be able to see who is online in order to match and message them. A limited number of the users online would be allowed on the screen and would be adjusted accordingly.   |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/23/2020| 
 |**Priority:** 2 |

**Comment by maiselkelly** [comment]
Created CSS Stylesheet for UI - KM

**Comment by maiselkelly** [comment]
Created Navigation Bar to route to other searches - KM

**Comment by UltimateStarCoder** [comment]
This looks good let's go with it.

**Comment by maiselkelly** [comment]
Okay, let's close the issue!
