### ISSUE TITLE
FR15: Route for user to pick matches by who is recommended

### ISSUE THREAD

**Issue by maiselkelly** [WSU-4110/Roomiez#21]
|FR15: Route for user to pick matches by who is recommended|
|---|
|**Goal**: To be able to view other users that are recommended to the user|
|**Stakeholders:** Customers|
| **Description:*Users would be able to see who their recommended matches are on the page. It would be arranged in the order of best match to least likely to be a match. The page would be adjusted as the user picks potential matches from the profiles.  |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/23/2020| 
 |**Priority:** 2 |

**Comment by maiselkelly** [comment]
Created CSS stylesheet for UI - KM

**Comment by maiselkelly** [comment]
Created navigation routes to other searches - KM

**Comment by ashrityschool** [comment]
Looks good Kelly! Nice job.

**Comment by maiselkelly** [comment]
Sweet, let's close the issue!
