### ISSUE TITLE
FR17: Route for user to pick matches by who is a new member

### ISSUE THREAD

**Issue by maiselkelly** [WSU-4110/Roomiez#23]
|FR17: Route for user to pick matches by who is a new member|
|---|
|**Goal**: For users to view new members |
|**Stakeholders:** Customers|
| **Description:*Users would be able to see who is new to the application. It would be arranged in the order of most recent. A limited number of the new members would be allowed on the screen and would be adjusted accordingly as the users stay in the app longer.  |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/23/2020| 
 |**Priority:** 2 |

**Comment by maiselkelly** [comment]
Created a CSS style sheet for the UI - KM

**Comment by maiselkelly** [comment]
Created navigation routes to other search routes

**Comment by ashrityschool** [comment]
Nice work on this FR, looking good.

**Comment by maiselkelly** [comment]
Alright team, I'll close the issue!
