### ISSUE TITLE
FR3: Update User Information

### ISSUE THREAD

**Issue by maiselkelly** [WSU-4110/Roomiez#3]
|FR3: Update User Information|
|---|
|**Goal**: The user will be able to change their profile information in the User Profile UI|
|**Stakeholders:** Customers|
| **Description:** The customer will be able to edit features of their profile after logging into Roomiez. They will be able to change their profile picture, the location, interests and any details that are in their user profile. These changes will save to the database and update for other users and themselves to be able to view in real time.  |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/23/2020|  
 |**Priority:** 1 |

**Comment by ashrityschool** [comment]
I came up with some prompts for updating the user information such as updating the username, entering the age, etc.
