### ISSUE TITLE
FR4. Create User Questionnaire 

### ISSUE THREAD

**Issue by maiselkelly** [WSU-4110/Roomiez#4]
|FR4.   Create User Questionnaire |
|---|
|**Goal**: The user questionnaire will match users with potential roommates that have similar selections as them|
|**Stakeholders:** Customers|
| **Description:** Customers will fill out a questionnaire related to how they are as a roommate as well as what they are looking for in a roommate. This feature will store the survey information into a database which will eventually be used to match users together by compatibility. However, this feature is simply creating the questionnaire and storing the results into the database. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/23/2020|  
 |**Priority:** 1 |

**Comment by ashrityschool** [comment]
The form submission isn't properly going through when the form is in two columns instead of one.

**Comment by ashrityschool** [comment]
Many questions were written to gather the personality of the user. The two column layout was acting up before but Kelly was able to fix it!
