### ISSUE TITLE
FR5. Home Tour (if renting out a room)

### ISSUE THREAD

**Issue by maiselkelly** [WSU-4110/Roomiez#5]
|FR5.  Home Tour (if renting out a room) |
|---|
|**Goal**: Users that are renting out a room will upload a video home tour|
|**Stakeholders:** Customers|
| **Description:** Users that are renting out a room will have a space where they are able to upload a video of their space for renters to view. This feature will be an inline video that is attached to the user profile of those that are renting out a space. The video can be removed and reposted if the space that is being rented has changed.. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/23/2020|  
 |**Priority:** 1 |

**Comment by UltimateStarCoder** [comment]
I added "<li><a href="/HomeTour">Home Tour</a></li>" to page 29 of UpdateUserProfile.html and also created the HomeTour.html as well... - MRU

**Comment by UltimateStarCoder** [comment]
I added Home Tour link to page 29 of UpdateUserProfile.html and also created the HomeTour.html as well... - MRU

**Comment by UltimateStarCoder** [comment]
The code works fine in the code preview but the CSS isn't being read in the LocalHost server

**Comment by UltimateStarCoder** [comment]
> The code works fine in the code preview but the CSS isn't being read in the LocalHost server

I also corrected all the errors in the whole codes as well

**Comment by UltimateStarCoder** [comment]
The code Requested in the Pull Request would be discarded because of server error when the css is not being read. have tried to fix it but haven't been able to.

**Comment by UltimateStarCoder** [comment]
Will start a new with a pull from Ashrit because his cod is still working well...

**Comment by ashrityschool** [comment]
Home Tour feature looking good Mac!

**Comment by UltimateStarCoder** [comment]
Done
