### ISSUE TITLE
NFR1:  User’s password will be encrypted to ensure safety (Security)

### ISSUE THREAD

**Issue by maiselkelly** [WSU-4110/Roomiez#8]
|NFR1:  User’s password will be encrypted to ensure safety (Security)|
|---|
|**Goal**: Users password information will be stored with password encryption in a database for security|
|**Stakeholders:** Customers|
| **Description:** When users create an account their user password will run through data encryption in order for their password and account information to not be hacked. This will also ensure security amongst user accounts in the database and in the website.  |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/23/2020| 
 |**Priority:** 1 |

**Comment by hmehryar** [comment]
Add the "Feature" label to rest of non-functional requirements

**Comment by maiselkelly** [comment]
User's password is encrypted with BCrypt!
