### ISSUE TITLE
NFR2: Users can view website from phone (Availability)

### ISSUE THREAD

**Issue by maiselkelly** [WSU-4110/Roomiez#9]
|NFR2: Users can view website from phone (Availability)|
|---|
|**Goal**: Users will be able to go to Roomiez.com on their cell phones and will have access to all of the features on the web browser|
|**Stakeholders:** Customers|
| **Description:** Users that have a Roomiez.com account will be able to use their phone’s web browser and will have access to all of the features that the web browser offers. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/23/2020| 
  |**Priority:** 1 |

**Comment by UltimateStarCoder** [comment]
I made some pages more responsive and have pushed it to my page. you can check it out and tell me what you think

**Comment by UltimateStarCoder** [comment]
I would add that adjustments to all of the other html files... see if you like it. And stop me if there is something wrong...

**Comment by ashrityschool** [comment]
Responsiveness looks great for the different possible devices.

**Comment by UltimateStarCoder** [comment]
The website should be responsive now.

**Comment by UltimateStarCoder** [comment]
> Responsiveness looks great for the different possible devices.

thanks
